using System.Globalization;
using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a non-interactive CE AA Script that invokes a UFunction with
/// pre-baked argument values. Designed for redistribution as part of a
/// Cheat Engine table -- the user enables the script and the function
/// fires once with the baked values, no UI interaction needed.
///
/// The generated script depends on <c>ue5_invoke_helper.lua</c> being
/// embedded in the same .CT via Table -> Add File... (see
/// <see cref="HelperFileResource"/> for the export action). At runtime the
/// script uses <c>findTableFile</c> to locate the helper and calls
/// <c>invokeUFunction</c> with the baked params table.
///
/// Sister to <see cref="InvokeScriptGenerator"/>:
/// <list type="bullet">
/// <item>InvokeScriptGenerator builds an in-CE form so the user fills
///     values at runtime in CE.</item>
/// <item>BakedScriptGenerator inlines the values at generation time and
///     produces a script ~5x smaller; the user fills values in the
///     UE5DumpUI dialog, then ships a static AA Script.</item>
/// </list>
/// Both use single-quoted Lua strings so the output transmits cleanly
/// through the AOBMaker JSON pipe.
/// </summary>
public static class BakedScriptGenerator
{
    /// <summary>Stable name of the embedded helper file the generated
    /// script will look up via <c>findTableFile</c>.</summary>
    public const string HelperFileName = "ue5_invoke_helper.lua";

    /// <summary>
    /// Generate a complete CE AA Script that invokes <paramref name="funcName"/>
    /// on a live instance of <paramref name="className"/> with the supplied
    /// baked parameter values.
    /// </summary>
    /// <param name="className">UClass name (e.g. "PlayerCharacter"). The
    ///     helper's CMD_INVOKE_BY_NAME path will <c>findInstance</c> live
    ///     non-CDO objects matching this name.</param>
    /// <param name="funcName">UFunction name (e.g. "AddMoney").</param>
    /// <param name="parmsSize">Total size of the function's params buffer
    ///     in bytes. The helper zero-fills this range before writing baked
    ///     values, so unsupplied params (e.g. return slot) start clean.</param>
    /// <param name="bakedValues">Param values to write. Pass an empty list
    ///     for void-return / no-arg functions; the generator will still
    ///     emit a clean invoke call.</param>
    /// <returns>A self-contained AA Script string with [ENABLE]/[DISABLE]
    ///     blocks. Trailing LF only (no CR) for CE compatibility.</returns>
    public static string Generate(
        string className,
        string funcName,
        int parmsSize,
        IReadOnlyList<BakedParamValue> bakedValues)
    {
        var sb = new StringBuilder(4096);

        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        Line(sb, "-- ================================================================");
        Line(sb, $"-- UFunction Invoker (baked args): {className}::{funcName}");
        Line(sb, "-- Generated by UE5CEDumper");
        Line(sb, "--");
        Line(sb, "-- REQUIREMENT: ue5_invoke_helper.lua MUST be embedded in this");
        Line(sb, "-- table via 'Table -> Add File...' (one-time setup per .CT).");
        Line(sb, "-- Get the file from UE5DumpUI: Tools -> Export CE Helper Lua File...");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Helper loader -- no filesystem fallback; explicit error on missing.
        AppendHelperLoader(sb);

        // Baked params table (or empty marker for no-arg functions)
        AppendBakedParamsTable(sb, bakedValues);

        // Invoke + result handling (silent on success, print + showMessage on error)
        AppendInvokeAndResultHandler(sb, className, funcName, parmsSize);

        // Auto-disable + close lua engine on success (your hygiene rule)
        AppendCleanupAndClose(sb);

        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "-- nop");
        Line(sb, "{$asm}");

        return sb.ToString();
    }

    // ------------------------------------------------------------------
    // Section emitters
    // ------------------------------------------------------------------

    private static void AppendHelperLoader(StringBuilder sb)
    {
        Line(sb, "-- Load helper from embedded table file (NO filesystem fallback)");
        Line(sb, $"local tf = findTableFile('{HelperFileName}')");
        Line(sb, "if not tf then");
        Line(sb, "  showMessage(");
        Line(sb, $"    '[Invoke] {HelperFileName} not found in this table.\\n\\n' ..");
        Line(sb, $"    'Setup: Table -> Add File... -> select {HelperFileName}\\n' ..");
        Line(sb, "    '(Export it from UE5DumpUI: Tools -> Export CE Helper Lua File)')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb, "do");
        Line(sb, "  local ss = createStringStream()");
        Line(sb, "  ss.copyFrom(tf.Stream, tf.Stream.Size)");
        Line(sb, "  local fn, err = load(ss.DataString)");
        Line(sb, "  ss.destroy()");
        Line(sb, "  if not fn then");
        Line(sb, "    showMessage('[Invoke] Helper load error:\\n' .. tostring(err))");
        Line(sb, "    if memrec then memrec.Active = false end");
        Line(sb, "    return");
        Line(sb, "  end");
        Line(sb, "  fn()");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendBakedParamsTable(
        StringBuilder sb, IReadOnlyList<BakedParamValue> values)
    {
        if (values.Count == 0)
        {
            Line(sb, "-- (no input params -- direct invoke)");
            Line(sb, "local PARAMS = {}");
            Line(sb);
            return;
        }

        Line(sb, "-- ====== BAKED PARAMS (edit values here) ==============================");
        Line(sb, "local PARAMS = {");
        foreach (var v in values)
        {
            var helperType = MapToHelperType(v.UeTypeName);
            var literal = RenderLiteral(v.UeTypeName, v.LiteralText);
            // Each row: { name='...', type='...', offset=N, value=LITERAL },  -- shortType
            Line(sb,
                $"  {{ name='{EscapeLua(v.ParamName)}', type='{helperType}', " +
                $"offset={v.Offset}, value={literal} }},  " +
                $"-- {ShortTypeNameForComment(v.UeTypeName)} {v.Size}B");
        }
        Line(sb, "}");
        Line(sb, "-- =====================================================================");
        Line(sb);
    }

    private static void AppendInvokeAndResultHandler(
        StringBuilder sb, string className, string funcName, int parmsSize)
    {
        Line(sb, "-- Invoke (silent on success -- only prints/showMessage on error)");
        Line(sb,
            $"local ok, err = invokeUFunction('{EscapeLua(className)}', " +
            $"'{EscapeLua(funcName)}', {parmsSize}, PARAMS)");
        Line(sb, "if not ok then");
        Line(sb, "  print(string.format('[Invoke] FAILED: %s::%s -- %s',");
        Line(sb, $"                      '{EscapeLua(className)}', " +
                  $"'{EscapeLua(funcName)}', tostring(err)))");
        Line(sb, "  showMessage('Invoke failed:\\n' .. tostring(err))");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendCleanupAndClose(StringBuilder sb)
    {
        Line(sb, "-- Auto-disable memrec; on success also close the lua engine window.");
        Line(sb, "-- (Errors leave the window open so you can read the message.)");
        Line(sb, "local t = createTimer(nil, false)");
        Line(sb, "t.Interval = 100");
        Line(sb, "t.OnTimer = function(s)");
        Line(sb, "  s.Enabled = false");
        Line(sb, "  s.destroy()");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  if ok then");
        Line(sb, "    synchronize(function() getLuaEngine().Close() end)");
        Line(sb, "  end");
        Line(sb, "end");
        Line(sb, "t.Enabled = true");
        Line(sb);
    }

    // ------------------------------------------------------------------
    // Type + literal helpers
    // ------------------------------------------------------------------

    /// <summary>
    /// Map a UE FProperty type name to the helper-recognised type token
    /// (see <c>writeBakedParams</c> in scripts/ue5_invoke_helper.lua).
    /// </summary>
    /// <remarks>
    /// All pointer-shaped types (object/class/name/soft/weak/lazy/interface/
    /// uint64) collapse to <c>'pointer'</c>; the helper writes them as a
    /// qword. Unrecognised types fall through to <c>'int32'</c> and the
    /// generator stamps a TODO in the literal so the user notices.
    /// </remarks>
    public static string MapToHelperType(string ueTypeName) => ueTypeName switch
    {
        "BoolProperty"                                => "bool",
        "ByteProperty" or "Int8Property"              => "byte",
        "Int16Property" or "UInt16Property"           => "int16",
        "IntProperty" or "UInt32Property" or "EnumProperty" => "int32",
        "Int64Property"                               => "int64",
        "UInt64Property"                              => "pointer",
        "FloatProperty"                               => "float",
        "DoubleProperty"                              => "double",
        "ObjectProperty" or "ClassProperty" or "NameProperty"
            or "SoftObjectProperty" or "SoftClassProperty"
            or "WeakObjectProperty" or "LazyObjectProperty"
            or "InterfaceProperty"                    => "pointer",
        _                                             => "int32",
    };

    /// <summary>
    /// Render a user-entered text value as a Lua numeric literal, picking
    /// the encoding (decimal int, decimal float, hex) by UE type. Falls
    /// back to a parenthesised raw expression with a TODO comment marker
    /// when parsing fails -- the generator never silently mangles input.
    /// </summary>
    public static string RenderLiteral(string ueTypeName, string text)
    {
        var t = (text ?? "").Trim();
        if (t.Length == 0) return "0";

        // Pointer-shaped types: prefer hex form
        if (ueTypeName is "ObjectProperty" or "ClassProperty" or "NameProperty"
            or "SoftObjectProperty" or "SoftClassProperty"
            or "WeakObjectProperty" or "LazyObjectProperty"
            or "InterfaceProperty" or "UInt64Property" or "Int64Property")
        {
            if (TryParseHexOrDecimal(t, out ulong u))
            {
                // Emit zero as plain "0" for readability; non-zero as 0xHEX
                return u == 0 ? "0" : $"0x{u:X}";
            }
            return MarkUnparsed(t);
        }

        // Bool: accept true/false/0/1/yes/no
        if (ueTypeName == "BoolProperty")
        {
            return ParseBoolLiteral(t) is { } b ? (b ? "1" : "0") : MarkUnparsed(t);
        }

        // Float / double: prefer InvariantCulture decimal
        if (ueTypeName is "FloatProperty" or "DoubleProperty")
        {
            if (double.TryParse(t, NumberStyles.Float, CultureInfo.InvariantCulture, out var d))
                return d.ToString("R", CultureInfo.InvariantCulture);
            return MarkUnparsed(t);
        }

        // Integer scalars (incl. enum/byte/int16): allow decimal or 0x form.
        // Emit as signed-decimal so negative values round-trip naturally; the
        // helper's writeBakedParams uses math.floor on the value so any
        // accidental fraction would be silently truncated upstream anyway.
        if (TryParseHexOrDecimal(t, out ulong i))
        {
            // If the user wrote 0x..., preserve the hex form for readability;
            // otherwise stick to decimal so negative inputs read naturally.
            if (t.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
                return $"0x{i:X}";
            return unchecked((long)i).ToString(CultureInfo.InvariantCulture);
        }
        return MarkUnparsed(t);
    }

    private static string MarkUnparsed(string raw)
        => $"--[[unparsed:{EscapeLuaComment(raw)}]] 0";

    private static bool TryParseHexOrDecimal(string text, out ulong value)
    {
        value = 0;
        var t = text.Trim();
        if (t.Length == 0) return false;

        // Negative decimal -> reinterpret as ulong (sign-preserved bit pattern)
        if (t.StartsWith("-", StringComparison.Ordinal))
        {
            if (long.TryParse(t, NumberStyles.Integer, CultureInfo.InvariantCulture, out var s))
            {
                value = unchecked((ulong)s);
                return true;
            }
            return false;
        }

        if (t.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
        {
            return ulong.TryParse(t.AsSpan(2), NumberStyles.HexNumber,
                                  CultureInfo.InvariantCulture, out value);
        }

        return ulong.TryParse(t, NumberStyles.Integer,
                              CultureInfo.InvariantCulture, out value);
    }

    private static bool? ParseBoolLiteral(string text) => text.ToLowerInvariant() switch
    {
        "true" or "1" or "yes" or "on"  => true,
        "false" or "0" or "no" or "off" => false,
        _                                => null,
    };

    /// <summary>Short type label rendered in the trailing comment of each
    /// PARAMS row (purely human-readable; not parsed).</summary>
    public static string ShortTypeNameForComment(string typeName) => typeName switch
    {
        "BoolProperty"   => "bool",
        "ByteProperty"   => "uint8",
        "Int8Property"   => "int8",
        "Int16Property"  => "int16",
        "UInt16Property" => "uint16",
        "IntProperty"    => "int32",
        "UInt32Property" => "uint32",
        "Int64Property"  => "int64",
        "UInt64Property" => "uint64",
        "FloatProperty"  => "float",
        "DoubleProperty" => "double",
        "EnumProperty"   => "enum(int32)",
        "NameProperty"   => "FName",
        "ObjectProperty" => "UObject*",
        "ClassProperty"  => "UClass*",
        _                => typeName.Replace("Property", ""),
    };

    /// <summary>Escape a string for embedding in a Lua single-quoted literal.</summary>
    public static string EscapeLua(string s)
        => s.Replace("\\", "\\\\")
            .Replace("'", "\\'")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r");

    /// <summary>Escape for embedding in a Lua block comment <c>--[[...]]</c>.
    /// The only sequence we have to break is a closing <c>]]</c> in the input;
    /// we pad it with a space so it can't terminate the comment early.</summary>
    private static string EscapeLuaComment(string s)
        => s.Replace("]]", "] ]");

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
