using System.Text;

namespace UE5DumpUI.Services;

/// <summary>
/// Shared CE-Lua "hygiene" emit helpers so every generated AA Script follows one
/// rule set:
/// <list type="bullet">
///   <item><b>Quiet by default.</b> Diagnostic <c>print()</c> is replaced by
///     <c>dbg()</c>, which only prints when the <c>DEBUG</c> flag is set. This
///     stops the CE Lua Engine window from popping over Cheat Engine on every
///     enable/disable.</item>
///   <item><b>Errors always surface.</b> Real failures keep using bare
///     <c>print()</c> / <c>showMessage()</c> so the user still sees them, and the
///     success-close is skipped so the window stays readable.</item>
///   <item><b>Auto-close on clean success.</b> When <c>DEBUG == 0</c> and the
///     block finished without error, the Lua Engine window closes itself.</item>
/// </list>
///
/// The flag is a single global master switch with a per-script override:
/// <c>local DEBUG = UE5_DEBUG or 0</c>. Set <c>UE5_DEBUG=1</c> once in CE's Lua
/// console to make every script verbose (and keep every window open), or edit a
/// single script's line to debug just that one. Default (unset) = quiet.
///
/// The emitted <c>dbg</c> definition is byte-identical everywhere so the
/// convention can't drift between generators; each generator places its own
/// success-close (<see cref="AppendCloseOnSuccess"/>) where its lifecycle allows.
/// </summary>
public static class CeLuaHygiene
{
    /// <summary>The exact Lua expression that closes the CE Lua Engine window.
    /// Kept as a shared constant so tests and every call site agree verbatim.</summary>
    public const string CloseCall = "synchronize(function() getLuaEngine().Close() end)";

    /// <summary>Project home — appended to every generated script's attribution so a
    /// shared .CT can be traced back. Single source of truth for the URL.</summary>
    public const string AttributionUrl = "https://github.com/bbfox0703/UE5CEDumper";

    /// <summary>The full attribution text (no comment prefix): the project name + URL.</summary>
    public const string Attribution = "Generated by UE5CEDumper | " + AttributionUrl;

    /// <summary>Emit the attribution as a Lua line comment. Place once near the top
    /// of a generated script (after the DEBUG preamble). LF-only.</summary>
    public static void AppendAttribution(StringBuilder sb, string indent = "")
    {
        sb.Append(indent).Append("-- ").Append(Attribution).Append('\n');
    }

    /// <summary>Emit the DEBUG preamble. Place it right after
    /// <c>if syntaxcheck then return end</c> in each <c>{$lua}</c> block that
    /// prints diagnostics or auto-closes. Every block is its own Lua chunk in CE,
    /// so locals don't cross blocks — emit this in each block that needs it.</summary>
    public static void AppendDebugPreamble(StringBuilder sb, string indent = "")
    {
        sb.Append(indent)
          .Append("local DEBUG = UE5_DEBUG or 0   -- 1 = show diagnostics + keep this window open\n");
        sb.Append(indent)
          .Append("local function dbg(...) if DEBUG ~= 0 then print(...) end end\n");
    }

    /// <summary>
    /// Escape arbitrary text for a Lua SINGLE-quoted literal. The one escaper new
    /// code should call — there are four divergent private copies in this repo
    /// (BakedScriptGenerator, FreezeScriptGenerator, InvokeScriptGenerator, plus
    /// EscapeLuaComment) and the weakest of them, InvokeScriptGenerator's, handles
    /// neither <c>\r</c> nor <c>\t</c> nor <c>]</c>.
    ///
    /// Handles backslash, single quote, LF, CR, TAB — and any closing long bracket
    /// (<c>]]</c>, <c>]=]</c>, <c>]==]</c>, …). That last one is not about Lua: the
    /// AOBMaker CE plugin wraps the WHOLE submitted script in <c>[==[ … ]==]</c> at a
    /// hardcoded level and does not escape the body, so the byte sequence must not
    /// appear anywhere in an emitted script — even inside a quoted string, where Lua
    /// itself would be perfectly happy. The leading <c>]</c> becomes the decimal
    /// escape <c>\093</c>: same runtime value, different source bytes. Three digits
    /// because <c>\ddd</c> greedily takes three (by construction the next emitted
    /// char here is <c>=</c> or <c>]</c>, never a digit, so it is belt-and-braces).
    ///
    /// A NUL cannot be escaped at all — <c>luaL_dostring</c> measures with
    /// <c>strlen</c> — so callers must reject it upstream (see
    /// <see cref="Models.CoordText.HasBlockedChars"/>).
    /// </summary>
    public static string EscapeLuaString(string? s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        var sb = new StringBuilder(s!.Length + 8);
        for (int i = 0; i < s.Length; i++)
        {
            char c = s[i];
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '\'': sb.Append("\\'");  break;
                case '\n': sb.Append("\\n");  break;
                case '\r': sb.Append("\\r");  break;
                case '\t': sb.Append("\\t");  break;
                case ']':
                {
                    int j = i + 1;
                    while (j < s.Length && s[j] == '=') j++;
                    sb.Append(j < s.Length && s[j] == ']' ? "\\093" : "]");
                    break;
                }
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }

    /// <summary>Emit the success-path close: closes the Lua Engine window unless
    /// <c>DEBUG</c> is on. Pass <paramref name="extraCondition"/> to gate on an
    /// additional Lua boolean expression (e.g. <c>"not hadError"</c>, <c>"ok"</c>)
    /// so error paths keep the window open.</summary>
    public static void AppendCloseOnSuccess(
        StringBuilder sb, string? extraCondition = null, string indent = "")
    {
        var cond = string.IsNullOrEmpty(extraCondition)
            ? "DEBUG == 0"
            : $"{extraCondition} and DEBUG == 0";
        sb.Append(indent).Append("if ").Append(cond)
          .Append(" then ").Append(CloseCall).Append(" end\n");
    }
}
