using System.Globalization;
using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Assembles a multi-row <see cref="CheatTableRow"/> selection into a
/// single Cheat Engine .CT file (XML). Output is structurally identical
/// to what CE produces via File -> Save As — same
/// <c>&lt;CheatTable CheatEngineTableVersion="46"&gt;</c> root,
/// <c>&lt;CheatEntries&gt;</c> nesting for groupable categories, and per-
/// row <c>&lt;AssemblerScript&gt;</c> bodies that CE evaluates as AA scripts
/// on entry-enable.
///
/// Generated layout:
/// <code>
/// CheatTable
///   CheatEntries
///     CheatEntry (root header "Generated by UE5CEDumper {timestamp}")
///       CheatEntries
///         CheatEntry (category header "Stats (N rows)")
///           CheatEntries
///             CheatEntry (one per row — AA Script entry)
///             ...
///         CheatEntry (next category header)
///           ...
/// </code>
///
/// Rows are grouped by <see cref="CheatTableRow.Category"/> with
/// alphabetical ordering for stable output; rows within a category
/// preserve input order (so the user can pre-sort by relevance in the
/// source panel and have that order survive). Uncategorised rows
/// (empty Category) land in a single "Uncategorised" bucket at the end.
///
/// XML escaping is applied to descriptions and the script body — CE's
/// XML reader is NOT CDATA-aware for AA Script bodies (existing .CT
/// exports demonstrate plain-text escaping for <c>&amp;lt;</c> etc.) so
/// we treat scripts as text content.
/// </summary>
public static class CheatTableBuilder
{
    /// <summary>CE table version emitted in the root element. Matches
    /// the version produced by current CE releases (7.5+). Older CE
    /// readers should still accept the file but unrecognised features
    /// degrade silently.</summary>
    public const int CheatEngineTableVersion = 46;

    /// <summary>Header colour for the root group (greenish — matches
    /// the bundled UE5CEDumper.CT root header style).</summary>
    public const string RootColor = "00BB5E";

    /// <summary>Header colour for category groups (purple-ish —
    /// distinguishes from the green root and the per-row default).</summary>
    public const string CategoryColor = "8000FF";

    /// <summary>Default starting ID for the root group. IDs in CE must
    /// be unique per table; we hand out sequential IDs from this base.
    /// Picking 1000 keeps space below for any user-edited IDs without
    /// risking collisions on a typical "merge into existing table"
    /// workflow.</summary>
    public const int BaseId = 1000;

    /// <summary>Build a complete .CT XML payload from a flat list of
    /// rows. Returns the full document including the
    /// <c>&lt;?xml version="1.0"...?&gt;</c> prolog.
    ///
    /// <paramref name="title"/> is embedded in the root group header so
    /// the user can identify the batch source at a glance — typically
    /// "Generated by UE5CEDumper (2026-05-27 16:42, 14 rows)" or a
    /// caller-specific label like "Interesting Properties — 5 rows".
    ///
    /// Throws on a null / empty rows list — empty CTs aren't useful and
    /// hiding the failure here would let a misbehaving caller ship a
    /// blank file. Caller is expected to gate the "Generate" button on
    /// <c>SelectedRows.Count &gt;= 1</c>.</summary>
    public static string Build(string title, IReadOnlyList<CheatTableRow> rows)
    {
        ArgumentNullException.ThrowIfNull(rows);
        if (rows.Count == 0)
            throw new ArgumentException("Cannot build a CT with zero rows.", nameof(rows));

        // Group rows by category preserving alphabetical order. Empty
        // category gets a single "Uncategorised" bucket at the END so
        // labelled rows lead the file.
        var grouped = new SortedDictionary<string, List<CheatTableRow>>(
            StringComparer.Ordinal);
        var uncategorised = new List<CheatTableRow>();
        foreach (var row in rows)
        {
            if (string.IsNullOrWhiteSpace(row.Category))
                uncategorised.Add(row);
            else
            {
                if (!grouped.TryGetValue(row.Category, out var bucket))
                {
                    bucket = new List<CheatTableRow>();
                    grouped[row.Category] = bucket;
                }
                bucket.Add(row);
            }
        }

        var sb = new StringBuilder(8192);
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
        sb.AppendLine($"<CheatTable CheatEngineTableVersion=\"{CheatEngineTableVersion}\">");
        sb.AppendLine("  <CheatEntries>");

        int id = BaseId;

        // --- Root group ---
        int rootId = id++;
        sb.AppendLine("    <CheatEntry>");
        sb.AppendLine($"      <ID>{rootId}</ID>");
        sb.AppendLine($"      <Description>\"{EscapeXml(title)}\"</Description>");
        sb.AppendLine($"      <Color>{RootColor}</Color>");
        sb.AppendLine("      <GroupHeader>1</GroupHeader>");
        sb.AppendLine("      <Options moHideChildren=\"1\" moDeactivateChildrenAsWell=\"1\"/>");
        sb.AppendLine("      <CheatEntries>");

        // --- Per-category groups ---
        // Ordered: alphabetical (grouped iterates in sorted-key order),
        // then Uncategorised last.
        foreach (var kv in grouped)
        {
            EmitCategoryGroup(sb, ref id, kv.Key, kv.Value);
        }
        if (uncategorised.Count > 0)
        {
            EmitCategoryGroup(sb, ref id, "Uncategorised", uncategorised);
        }

        sb.AppendLine("      </CheatEntries>");
        sb.AppendLine("    </CheatEntry>");

        sb.AppendLine("  </CheatEntries>");
        sb.AppendLine("  <UserdefinedSymbols/>");
        sb.AppendLine("</CheatTable>");
        return sb.ToString();
    }

    /// <summary>Default save-as filename. Format
    /// <c>{processName}-batch-{yyyyMMdd-HHmmss}.CT</c> — descriptive
    /// enough that multiple batches across a session don't collide,
    /// short enough to fit comfortably in a save dialog.
    /// <paramref name="processName"/> falls back to "UE5CEDumper" when
    /// the caller doesn't have an attached process; the timestamp is
    /// ISO-style (sortable filename) in local time.</summary>
    public static string DefaultFileName(string? processName, DateTime now)
    {
        string proc = string.IsNullOrWhiteSpace(processName)
            ? "UE5CEDumper" : SanitizeFileName(processName);
        return $"{proc}-batch-{now:yyyyMMdd-HHmmss}.CT";
    }

    // ------------------------------------------------------------------
    // Internal helpers
    // ------------------------------------------------------------------

    private static void EmitCategoryGroup(
        StringBuilder sb, ref int id, string category, List<CheatTableRow> rows)
    {
        int categoryId = id++;
        sb.AppendLine("        <CheatEntry>");
        sb.AppendLine($"          <ID>{categoryId}</ID>");
        sb.AppendLine(
            $"          <Description>\"--- {EscapeXml(category)} " +
            $"({rows.Count} row{(rows.Count == 1 ? "" : "s")}) ---\"" +
            "</Description>");
        sb.AppendLine($"          <Color>{CategoryColor}</Color>");
        sb.AppendLine("          <GroupHeader>1</GroupHeader>");
        sb.AppendLine("          <CheatEntries>");
        foreach (var row in rows)
        {
            EmitRowEntry(sb, ref id, row);
        }
        sb.AppendLine("          </CheatEntries>");
        sb.AppendLine("        </CheatEntry>");
    }

    private static void EmitRowEntry(StringBuilder sb, ref int id, CheatTableRow row)
    {
        int rowId = id++;
        string script = row.GenerateScript();

        sb.AppendLine("            <CheatEntry>");
        sb.AppendLine($"              <ID>{rowId}</ID>");
        sb.AppendLine(
            $"              <Description>\"{EscapeXml(row.Description)}\"</Description>");
        sb.AppendLine("              <VariableType>Auto Assembler Script</VariableType>");
        // AssemblerScript body — CE expects raw text with XML special
        // chars escaped. The script body may contain newlines (it
        // typically does — multi-line Lua); we emit them verbatim,
        // matching the existing UE5CEDumper.CT export style. CR/LF
        // normalisation: our generators emit LF only, so output is
        // platform-neutral.
        sb.Append("              <AssemblerScript>");
        sb.Append(EscapeXml(script));
        sb.AppendLine("</AssemblerScript>");
        sb.AppendLine("            </CheatEntry>");
    }

    /// <summary>XML-escape text content. Handles the five canonical
    /// entities; we don't bother with numeric character references
    /// because CE happily round-trips them when re-saving.</summary>
    internal static string EscapeXml(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        var sb = new StringBuilder(s.Length + 16);
        foreach (var c in s)
        {
            switch (c)
            {
                case '&':  sb.Append("&amp;");  break;
                case '<':  sb.Append("&lt;");   break;
                case '>':  sb.Append("&gt;");   break;
                case '"':  sb.Append("&quot;"); break;
                case '\'': sb.Append("&apos;"); break;
                default:   sb.Append(c);        break;
            }
        }
        return sb.ToString();
    }

    /// <summary>Strip filename-illegal characters from a process name.
    /// Windows + cross-platform — drops the union of
    /// <see cref="Path.GetInvalidFileNameChars"/> + a small set of
    /// confusables (space → _, etc.) that hurt double-click usability.</summary>
    internal static string SanitizeFileName(string name)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
        {
            if (Array.IndexOf(invalid, c) >= 0)
                sb.Append('_');
            else if (c == ' ')
                sb.Append('_');
            else
                sb.Append(c);
        }
        // Trim trailing dots / spaces — Windows treats them as invalid.
        return sb.ToString().TrimEnd('.', '_', ' ');
    }
}
