using System.Text;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a CE memory-record AA Script for the robust Debug Camera toggle.
///
/// Unlike <see cref="BakedScriptGenerator"/> (a one-shot invoke whose
/// <c>[DISABLE]</c> is a nop), this is a STATEFUL checkbox: ticking runs
/// <c>[ENABLE]</c> → <c>setDebugCamera(1)</c> (camera ON), unticking runs
/// <c>[DISABLE]</c> → <c>setDebugCamera(0)</c> (camera OFF). Both blocks load
/// <c>ue5_invoke_helper.lua</c> (embedded in the .CT) and call the shared
/// <c>setDebugCamera</c> wrapper, which forwards to the <c>UE5_SetDebugCamera</c>
/// DLL export — so the whole toggle + controller-swap fallback (for Shipping
/// builds that strip <c>DisableDebugCamera</c>) runs DLL-side, identical to the
/// Console panel's Force On / Force Off.
/// </summary>
public static class DebugCameraScriptGenerator
{
    /// <summary>Build the [ENABLE]/[DISABLE] memory-record script.</summary>
    public static string Generate()
    {
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", enable: true);
        EmitBlock(sb, "[DISABLE]", enable: false);
        return sb.ToString();
    }

    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData):
    //   0x00 cmd (write LAST to trigger), 0x04 status (poll == 1), 0x08 result,
    //   0x10 instanceAddr (here: the request 0=OFF / 1=ON). CMD_SET_DEBUG_CAMERA=7.
    private static void EmitBlock(StringBuilder sb, string header, bool enable)
    {
        var label = enable ? "ON" : "OFF";
        var req   = enable ? 1 : 0;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        Line(sb, "-- ================================================================");
        Line(sb, $"-- Debug Camera force {label} -- Generated by UE5CEDumper");
        Line(sb, "-- Tick = camera ON, untick = camera OFF. SELF-CONTAINED: talks to");
        Line(sb, "-- UE5Dumper.dll's mailbox directly -- no ue5_invoke_helper.lua");
        Line(sb, "-- needed. The DLL toggles and, when the game can't disable, switches");
        Line(sb, "-- the player's controller back to the original PlayerController.");
        Line(sb, "-- Requires UE5Dumper.dll injected (version.dll proxy or CE inject).");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Resolve the exported mailbox symbol (tolerate the module-qualified form).
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "  showMessage('[DebugCamera] g_invokeMailbox not found -- is " +
                  "UE5Dumper.dll injected?')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb);

        // Mailbox round-trip: write request, trigger CMD_SET_DEBUG_CAMERA=7, poll.
        Line(sb, $"writeQword(mb + 0x10, {req})   -- request: {req} = {label}");
        Line(sb, "writeInteger(mb + 0x04, 0)    -- clear status");
        Line(sb, "writeInteger(mb + 0x00, 7)    -- CMD_SET_DEBUG_CAMERA (write LAST)");
        Line(sb, "local elapsed = 0");
        Line(sb, "while readInteger(mb + 0x04) ~= 1 do");
        Line(sb, "  sleep(1)");
        Line(sb, "  elapsed = elapsed + 1");
        Line(sb, "  if elapsed >= 10000 then");
        Line(sb, "    showMessage('[DebugCamera] mailbox timeout (DLL not responding?)')");
        Line(sb, "    return");
        Line(sb, "  end");
        Line(sb, "end");
        Line(sb, "local state = readInteger(mb + 0x08)   -- 1=ON, 0=OFF, -1=error");
        Line(sb, $"print('[DebugCamera] {label} -> state=' .. tostring(state))");
        Line(sb, "if state == -1 then");
        Line(sb, $"  showMessage('[DebugCamera] {label} -- no live CheatManager? " +
                  "(enter gameplay first)')");
        Line(sb, "end");
        Line(sb, "{$asm}");
    }

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
