using System.Text;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a CE memory-record AA Script for the robust Debug Camera toggle.
///
/// Unlike <see cref="BakedScriptGenerator"/> (a one-shot invoke whose
/// <c>[DISABLE]</c> is a nop), this is a STATEFUL checkbox: ticking runs
/// <c>[ENABLE]</c> → <c>setDebugCamera(1)</c> (camera ON), unticking runs
/// <c>[DISABLE]</c> → <c>setDebugCamera(0)</c> (camera OFF). Both blocks load
/// <c>ue5_invoke_helper.lua</c> (embedded in the .CT) and call the shared
/// <c>setDebugCamera</c> wrapper, which forwards to the <c>UE5_SetDebugCamera</c>
/// DLL export — so the whole toggle + controller-swap fallback (for Shipping
/// builds that strip <c>DisableDebugCamera</c>) runs DLL-side, identical to the
/// Console panel's Force On / Force Off.
/// </summary>
public static class DebugCameraScriptGenerator
{
    /// <summary>Build the [ENABLE]/[DISABLE] memory-record script.</summary>
    public static string Generate()
    {
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", enable: true);
        EmitBlock(sb, "[DISABLE]", enable: false);
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, string header, bool enable)
    {
        var label = enable ? "ON" : "OFF";
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        Line(sb, "-- ================================================================");
        Line(sb, $"-- Debug Camera force {label} -- Generated by UE5CEDumper");
        Line(sb, "-- Tick = camera ON, untick = camera OFF (robust: the DLL toggles");
        Line(sb, "-- and, when the game can't disable, switches the player's controller");
        Line(sb, "-- back to the original PlayerController).");
        Line(sb, "--");
        Line(sb, "-- REQUIREMENT: ue5_invoke_helper.lua MUST be embedded in this table");
        Line(sb, "-- (Table -> Add File...). Export it from UE5DumpUI: Tools -> Export");
        Line(sb, "-- CE Helper Lua File...");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Reuse the exact, proven helper-load preamble. It defines the global
        // setDebugCamera (re-declaration-safe), so loading in BOTH blocks is
        // idempotent and survives an untick-before-tick / engine reset.
        BakedScriptGenerator.AppendHelperLoader(sb);

        Line(sb, $"local ok, _state = pcall(setDebugCamera, {(enable ? 1 : 0)})");
        Line(sb, "if not ok then");
        Line(sb, $"  showMessage('[DebugCamera] {label} failed:\\n' .. tostring(_state))");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb, $"print(string.format('[DebugCamera] {label} -> state=%s', tostring(_state)))");
        Line(sb, "if _state == -1 then");
        Line(sb, $"  showMessage('[DebugCamera] {label} -- no live CheatManager? " +
                  "(enter gameplay first)')");
        Line(sb, "end");
        Line(sb, "{$asm}");
    }

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
