using System.Collections.Generic;
using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a CE memory-record AA Script for the Fly toggles (Dunste) that call
/// the injected UE5Dumper.dll via the mailbox — the DLL-driven counterpart to the
/// pure-Lua standalone-trainer fly.
///
/// Two STATEFUL checkboxes (like <see cref="ProtectionScriptGenerator"/>):
///   • <see cref="FlyToggle.Enabled"/> — <c>[ENABLE]</c> fires <c>CMD_FLY</c> op
///     <c>FLY_OP_SET_ENABLED</c> value 1 (force MOVE_Flying + start the worker),
///     <c>[DISABLE]</c> value 0 (restore MovementMode).
///   • <see cref="FlyToggle.Noclip"/> — op <c>FLY_OP_SET_NOCLIP</c> value 1/0
///     (disable / restore the actor's collision so flight passes through walls).
///
/// SELF-CONTAINED: talks to the DLL mailbox directly (no ue5_invoke_helper.lua).
/// The DLL owns the reflection, the MOVE_Flying hold, the keyboard read, and the
/// velocity drive (input is sampled DLL-side, so the toggle only arms/disarms).
/// </summary>
public static class FlyScriptGenerator
{
    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData + FlyOp):
    //   0x00 cmd (write LAST to trigger) = CMD_FLY(11)
    //   0x04 status (poll == 1), 0x08 result (1 active / 0 off / negative FlyResult)
    //   0x10 instanceAddr = op  (FLY_OP_SET_ENABLED=0 / FLY_OP_SET_NOCLIP=4)
    //   0x18 ufuncAddr    = value (1 = ON / 0 = OFF)
    private const int CmdFly = CeMailboxLayout.CmdFly;

    /// <summary>Which Fly toggle to emit — the enum value IS the mailbox op.</summary>
    public enum FlyToggle
    {
        Enabled = 0,   // FLY_OP_SET_ENABLED
        Noclip  = 4,   // FLY_OP_SET_NOCLIP
    }

    private static string Name(FlyToggle t) => t == FlyToggle.Noclip ? "Fly Noclip" : "Fly";

    /// <summary>Build the [ENABLE]/[DISABLE] memory-record script for one toggle.</summary>
    public static string Generate(FlyToggle toggle)
    {
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", toggle, enable: true);
        EmitBlock(sb, "[DISABLE]", toggle, enable: false);
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, string header, FlyToggle toggle, bool enable)
    {
        string name  = Name(toggle);
        string label = enable ? "ON" : "OFF";
        int    op    = (int)toggle;
        int    value = enable ? 1 : 0;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- {name} force {label} -- Generated by UE5CEDumper | {CeLuaHygiene.AttributionUrl}");
        if (toggle == FlyToggle.Noclip)
        {
            Line(sb, "-- Tick = Noclip ON (disable the pawn's collision so flight passes");
            Line(sb, "-- through walls), untick = OFF (restore collision).");
        }
        else
        {
            Line(sb, "-- Tick = Fly ON (force MOVE_Flying, no gravity), untick = OFF.");
            Line(sb, "-- Movement keys are read DLL-side (view-relative WASD + up/down);");
            Line(sb, "-- keep the GAME window focused. Turn with the mouse.");
        }
        Line(sb, "-- SELF-CONTAINED: talks to UE5Dumper.dll's mailbox directly -- no");
        Line(sb, "-- ue5_invoke_helper.lua needed. Requires UE5Dumper.dll injected");
        Line(sb, "-- (version.dll proxy or CE inject). Single-player only.");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Resolve the exported mailbox symbol (tolerate the module-qualified form).
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, $"  showMessage('[{name}] g_invokeMailbox not found -- is " +
                  "UE5Dumper.dll injected?')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb);

        // Mailbox round-trip: write op + value, trigger CMD_FLY=11, poll status.
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffInstanceAddr}, {op})    -- op: FLY_OP_SET_{(toggle == FlyToggle.Noclip ? "NOCLIP" : "ENABLED")}");
        Line(sb, $"writeQword(mb + {CeMailboxLayout.OffUfuncAddr}, {value})    -- value: {value} = {label}");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffStatus}, 0)    -- clear status");
        Line(sb, $"writeInteger(mb + {CeMailboxLayout.OffCmd}, {CmdFly})    -- CMD_FLY (write LAST)");
        Line(sb, "local elapsed = 0");
        Line(sb, $"while readInteger(mb + {CeMailboxLayout.OffStatus}) ~= 1 do");
        Line(sb, "  sleep(1)");
        Line(sb, "  elapsed = elapsed + 1");
        Line(sb, $"  if elapsed >= {CeMailboxLayout.MailboxPollTimeoutMs} then");
        Line(sb, $"    showMessage('[{name}] mailbox timeout (DLL not responding?)')");
        Line(sb, "    return");
        Line(sb, "  end");
        Line(sb, "end");
        Line(sb, $"local state = readInteger(mb + {CeMailboxLayout.OffResult})   -- 1=active, 0=off, <0=error");
        Line(sb, $"dbg('[{name}] {label} -> state=' .. tostring(state))");
        Line(sb, "if state < 0 then");
        Line(sb, $"  showMessage('[{name}] {label} -- no pawn / no CharacterMovement? (enter gameplay first)')");
        Line(sb, "elseif DEBUG == 0 then");
        Line(sb, $"  {CeLuaHygiene.CloseCall}   -- clean success: close the Lua Engine window");
        Line(sb, "end");
        Line(sb, "{$asm}");
    }

    /// <summary>Build the .CT batch rows (Fly + Fly Noclip) for
    /// <see cref="CheatTableBuilder.Build"/>.</summary>
    public static List<CheatTableRow> BuildBatchRows()
    {
        return new List<CheatTableRow>
        {
            new CtScriptRow
            {
                Category = "Fly",
                Description = "Fly (no-gravity 3D flight)",
                Script = Generate(FlyToggle.Enabled),
            },
            new CtScriptRow
            {
                Category = "Fly",
                Description = "Fly Noclip (through walls)",
                Script = Generate(FlyToggle.Noclip),
            },
        };
    }

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
