using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a CE AA Script that locks a UE property value across ALL
/// live instances of a class. The generated script depends on
/// <c>ue5_freeze_helper.lua</c> being embedded in the .CT via
/// <see cref="IAobMakerBridge.InjectTableFileAsync"/> (or manual
/// <c>Table -&gt; Add File...</c>); at runtime it loads the helper and
/// calls <c>freezeProperty(cfg)</c>, then <c>handle.start()</c> /
/// <c>handle.stop()</c> from the [ENABLE] / [DISABLE] blocks.
///
/// Mirror of <see cref="BakedScriptGenerator"/> for the freeze use case:
/// single-quoted Lua strings for clean transit through the AOBMaker JSON
/// pipe, trailing LF (no CR), self-contained helper-loader prologue.
/// </summary>
public static class FreezeScriptGenerator
{
    /// <summary>Stable name of the embedded helper file the generated
    /// script looks up via <c>findTableFile</c>. Must match
    /// <see cref="FreezeHelperLuaResource.DefaultFileName"/>.</summary>
    public const string HelperFileName = "ue5_freeze_helper.lua";

    /// <summary>
    /// Build the AA Script for one freeze tuple. The output is a complete
    /// AA Script string with <c>[ENABLE]</c> / <c>[DISABLE]</c> blocks --
    /// enabling the script starts the freeze, disabling it stops cleanly.
    /// </summary>
    public static string Generate(FreezeScriptParams p)
    {
        var helperType = MapToHelperType(p.UeTypeName);
        var sb = new StringBuilder(2048);

        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- Property Freeze: {p.ClassName}::{p.PropertyName}");
        Line(sb, $"-- Generated by UE5CEDumper | {CeLuaHygiene.AttributionUrl}");
        Line(sb, "--");
        Line(sb, "-- REQUIREMENT: ue5_freeze_helper.lua MUST be embedded in this");
        Line(sb, "-- table. Inject via UE5DumpUI:");
        Line(sb, "--   Tools -> Inject Freeze Helper into Current CE Table");
        Line(sb, "-- ================================================================");
        Line(sb);

        // CFG block FIRST so the human eye lands on the editable values.
        AppendCfgBlock(sb, p, helperType);

        // Helper loader -- mirrors BakedScriptGenerator's prologue.
        AppendHelperLoader(sb);

        // Handles are stashed in a shared global table keyed by the
        // (class, prop, offset) tuple so multiple freeze scripts coexist
        // in the same CE Lua engine without clobbering each other's
        // handle. The key string is deterministic -- re-enabling the
        // same script re-uses the same slot.
        var handleKey = $"{p.ClassName}::{p.PropertyName}@0x{p.PropertyOffset:X}";

        Line(sb, "-- Per-script keyed handle storage so multiple Freeze scripts");
        Line(sb, "-- coexist in the same Lua engine without clobbering each other.");
        Line(sb, "_ue5_freeze_handles = _ue5_freeze_handles or {}");
        Line(sb, $"local FREEZE_KEY = '{EscapeLua(handleKey)}'");
        Line(sb);
        Line(sb, "-- Defensive stop: if a previous activation didn't clean up");
        Line(sb, "-- (rare -- AA Script reload while active), drop the stale handle.");
        Line(sb, "if _ue5_freeze_handles[FREEZE_KEY] then");
        Line(sb, "  pcall(_ue5_freeze_handles[FREEZE_KEY].stop)");
        Line(sb, "  _ue5_freeze_handles[FREEZE_KEY] = nil");
        Line(sb, "end");
        Line(sb);
        Line(sb, "-- Build the freeze handle from CFG and start the timers.");
        Line(sb, "local ok, handleOrErr = pcall(freezeProperty, CFG)");
        Line(sb, "if not ok then");
        Line(sb, "  showMessage('[Freeze] freezeProperty error:\\n' .. tostring(handleOrErr))");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb, "_ue5_freeze_handles[FREEZE_KEY] = handleOrErr");
        Line(sb, "local sok, serr = pcall(handleOrErr.start)");
        Line(sb, "if not sok then");
        Line(sb, "  _ue5_freeze_handles[FREEZE_KEY] = nil");
        Line(sb, "  showMessage('[Freeze] start error:\\n' .. tostring(serr))");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb,
            $"dbg(string.format('[Freeze] Started: {EscapeLua(p.ClassName)}::" +
            $"{EscapeLua(p.PropertyName)} = %s ({helperType}@0x{p.PropertyOffset:X})', " +
            "tostring(CFG.value)))");
        // Freeze timers are now running -- close the Lua Engine window on a clean start.
        CeLuaHygiene.AppendCloseOnSuccess(sb);
        Line(sb);
        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "_ue5_freeze_handles = _ue5_freeze_handles or {}");
        Line(sb, $"local FREEZE_KEY = '{EscapeLua(handleKey)}'");
        Line(sb, "local h = _ue5_freeze_handles[FREEZE_KEY]");
        Line(sb, "if h then");
        Line(sb, "  pcall(h.stop)");
        Line(sb, "  _ue5_freeze_handles[FREEZE_KEY] = nil");
        Line(sb,
            $"  dbg('[Freeze] Stopped: {EscapeLua(p.ClassName)}::" +
            $"{EscapeLua(p.PropertyName)}')");
        Line(sb, "end");
        // Clean untick -- close the Lua Engine window.
        CeLuaHygiene.AppendCloseOnSuccess(sb);
        Line(sb, "{$asm}");

        return sb.ToString();
    }

    // ------------------------------------------------------------------
    // Section emitters
    // ------------------------------------------------------------------

    private static void AppendCfgBlock(
        StringBuilder sb, FreezeScriptParams p, string helperType)
    {
        Line(sb, "-- ====== EDIT VALUES BELOW =============================================");
        Line(sb, "local CFG = {");
        Line(sb, $"  className          = '{EscapeLua(p.ClassName)}',");
        Line(sb, $"  propOffset         = 0x{p.PropertyOffset:X},");
        Line(sb, $"  valueType          = '{helperType}',");
        Line(sb, $"  value              = {p.ValueLiteral},");
        Line(sb, "  tickIntervalMs     = 50,    -- writes 20x/sec; lower = more CPU");
        Line(sb, "  refreshIntervalSec = 5,     -- re-enum instances every 5s");
        Line(sb, "  -- filter = function(addr) return true end,  -- optional");
        Line(sb, "}");
        Line(sb, "-- =====================================================================");
        Line(sb);
    }

    private static void AppendHelperLoader(StringBuilder sb)
    {
        Line(sb, "-- Load ue5_freeze_helper.lua from the table file (no fs fallback).");
        Line(sb, $"local tf = findTableFile('{HelperFileName}')");
        Line(sb, "if not tf then");
        Line(sb, "  showMessage(");
        Line(sb, $"    '[Freeze] {HelperFileName} not found in this table.\\n\\n' ..");
        Line(sb, "    'Setup: UE5DumpUI -> Tools -> Inject Freeze Helper into Current CE Table')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb, "do");
        Line(sb, "  local ss = createStringStream()");
        // copyFrom (not Stream.write) -- consistent with invoke helper's loader
        // and the CE Lua quirk noted in memory (Stream.write copies forward,
        // copyFrom is the safe reverse).
        Line(sb, "  ss.copyFrom(tf.Stream, tf.Stream.Size)");
        Line(sb, "  local fn, err = load(ss.DataString)");
        Line(sb, "  ss.destroy()");
        Line(sb, "  if not fn then");
        Line(sb, "    showMessage('[Freeze] Helper load error:\\n' .. tostring(err))");
        Line(sb, "    if memrec then memrec.Active = false end");
        Line(sb, "    return");
        Line(sb, "  end");
        Line(sb, "  fn()");
        Line(sb, "end");
        Line(sb);
    }

    // ------------------------------------------------------------------
    // Type mapping (UE -> ue5_freeze_helper.lua valueType)
    // ------------------------------------------------------------------

    /// <summary>
    /// Map a UE property type string (e.g. "FloatProperty") to the
    /// freeze helper's <c>valueType</c> string. Unsupported / unknown
    /// types map to the empty string so callers can detect them and
    /// gray out the freeze button at the row level.
    /// </summary>
    public static string MapToHelperType(string ueTypeName) => ueTypeName switch
    {
        "BoolProperty"   => "bool",
        "ByteProperty"   => "uint8",
        "Int8Property"   => "int8",
        "Int16Property"  => "int16",
        "UInt16Property" => "uint16",
        "IntProperty"    => "int32",
        "UInt32Property" => "uint32",
        // EnumProperty stores the underlying integer; UE almost always uses
        // a 1-byte or 4-byte underlying type but the SizeOf is what matters
        // and the helper handles either via the int writers. Default to
        // int32 here -- if a future game has a 1-byte enum we'd want to
        // surface the size and pick uint8 instead. Out of v1 scope.
        "EnumProperty"   => "int32",
        "Int64Property"  => "int64",
        "UInt64Property" => "uint64",
        "FloatProperty"  => "float",
        "DoubleProperty" => "double",
        _                => "",
    };

    /// <summary>
    /// Whether the given UE property type is supported by v1 of the
    /// freeze pipeline. Used by the row-level button enablement so
    /// users don't get a script that the helper would reject.
    /// </summary>
    public static bool IsTypeSupported(string ueTypeName)
        => !string.IsNullOrEmpty(MapToHelperType(ueTypeName));

    // ------------------------------------------------------------------
    // Lua escaping
    // ------------------------------------------------------------------

    /// <summary>
    /// Escape a string for embedding inside single-quoted Lua literals.
    /// Mirrors BakedScriptGenerator's escape rules.
    /// </summary>
    public static string EscapeLua(string s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        var sb = new StringBuilder(s.Length + 8);
        for (int i = 0; i < s.Length; i++)
        {
            char ch = s[i];
            switch (ch)
            {
                case '\\': sb.Append("\\\\"); break;
                case '\'': sb.Append("\\'"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case ']':
                {
                    // See BakedScriptGenerator.EscapeLua: a closing long bracket of
                    // any level would terminate AOBMaker's [==[ ... ]==] wrapper
                    // around the whole script. Inputs here are engine-derived today,
                    // but the escapers are documented mirrors -- keep them mirrors.
                    int j = i + 1;
                    while (j < s.Length && s[j] == '=') j++;
                    sb.Append(j < s.Length && s[j] == ']' ? "\\093" : "]");
                    break;
                }
                default:   sb.Append(ch);    break;
            }
        }
        return sb.ToString();
    }

    private static void Line(StringBuilder sb, string s = "") => sb.Append(s).Append('\n');
}
