using System.Collections.Generic;
using System.Globalization;
using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates CE memory-record AA Scripts for the movement-tuning knobs (Laufen):
/// Move Speed / Gravity / Super Jump. Each is a STATEFUL toggle (like
/// <see cref="ProtectionScriptGenerator"/>): ticking runs <c>[ENABLE]</c> →
/// mailbox <c>CMD_MOVEMENT=10</c> with the baked percent; unticking runs
/// <c>[DISABLE]</c> → percent 100 (which the DLL treats as OFF / restore base).
///
/// SELF-CONTAINED: talks to the UE5Dumper.dll mailbox directly — no helper Lua.
/// The DLL owns the reflection, the base-value cache, the height→velocity √ (for
/// Super Jump) and the re-assert worker (so the value survives respawns while the
/// record is ticked). The "100% = OFF" rule is decided DLL-side
/// (<c>Laufen::SetKnobPercent</c>), so the script just sends a percentage.
/// </summary>
public static class MovementScriptGenerator
{
    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData + Cmd):
    //   0x00 cmd (write LAST to trigger) = CMD_MOVEMENT(10)
    //   0x04 status (poll == 1), 0x08 result (1 active / 0 off / negative error)
    //   0x10 instanceAddr = knobId (0 MaxWalkSpeed / 1 GravityScale / 2 JumpZVelocity)
    //   0x328 paramsData[0..7] = double percent (100 = off; knob 2 = jump HEIGHT %)
    private const int CmdMovement = 10;

    /// <summary>The three tunable knobs — value is the mailbox knobId.</summary>
    public enum Knob { WalkSpeed = 0, Gravity = 1, Jump = 2 }

    /// <summary>Build a stateful [ENABLE]/[DISABLE] record for one knob baked at
    /// <paramref name="percent"/> (the current slider %). For
    /// <see cref="Knob.Jump"/> the percent is jump HEIGHT %.</summary>
    public static string Generate(Knob knob, double percent)
    {
        string label = Label(knob);
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", knob, label, percent, enable: true);
        EmitBlock(sb, "[DISABLE]", knob, label, percent, enable: false);
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, string header, Knob knob,
        string label, double percent, bool enable)
    {
        // [DISABLE] always sends 100% — the DLL reads that as OFF (restore base).
        double sent = enable ? percent : 100.0;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        if (enable)
        {
            Line(sb, "-- ================================================================");
            Line(sb, $"-- Movement: {label} {Pct(percent)} -- Generated by UE5CEDumper (self-contained)");
            Line(sb, $"-- Tick = apply {Pct(percent)} (held by the DLL re-assert worker), untick = OFF.");
            Line(sb, "-- Talks to UE5Dumper.dll's mailbox directly (CMD_MOVEMENT=10). 100% = OFF.");
            Line(sb, $"-- {knob switch { Knob.Jump => "Jump slider is HEIGHT %; the DLL applies sqrt to JumpZVelocity.", _ => "Percent multiplies the captured base value." }}");
            Line(sb, "-- Requires UE5Dumper.dll injected (version.dll proxy or CE inject).");
            Line(sb, "-- ================================================================");
        }
        else
        {
            Line(sb, $"-- Movement: {label} OFF (send 100% -> DLL restores the captured base).");
        }
        Line(sb);
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        if (enable)
        {
            Line(sb, "  showMessage('[Movement] g_invokeMailbox not found -- is UE5Dumper.dll injected?')");
            Line(sb, "  if memrec then memrec.Active = false end");
        }
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb);
        Line(sb, $"writeQword(mb + 0x10, {(int)knob})        -- knobId: {label}");
        Line(sb, $"writeDouble(mb + 0x328, {Lua(sent)})   -- percent (100 = off)");
        Line(sb, "writeInteger(mb + 0x04, 0)        -- clear status");
        Line(sb, $"writeInteger(mb + 0x00, {CmdMovement})       -- CMD_MOVEMENT (write LAST)");
        Line(sb, "local elapsed = 0");
        Line(sb, "while readInteger(mb + 0x04) ~= 1 do");
        Line(sb, "  sleep(1); elapsed = elapsed + 1");
        if (enable)
        {
            Line(sb, "  if elapsed >= 10000 then");
            Line(sb, "    showMessage('[Movement] mailbox timeout (DLL not responding?)')");
            Line(sb, "    return");
            Line(sb, "  end");
        }
        else
        {
            Line(sb, "  if elapsed >= 10000 then break end");
        }
        Line(sb, "end");
        if (enable)
        {
            Line(sb, "local state = readInteger(mb + 0x08)   -- 1=active, 0=off, <0=error");
            Line(sb, $"print('[Movement] {label} {Pct(percent)} -> state=' .. tostring(state))");
            Line(sb, "if state < 0 then");
            Line(sb, $"  showMessage('[Movement] {label} -- no pawn / no CharacterMovement (enter gameplay first)')");
            Line(sb, "end");
        }
        Line(sb, "{$asm}");
    }

    /// <summary>Build the 3-row .CT batch (Move Speed / Gravity / Super Jump) baked
    /// at the current slider percentages, ready for
    /// <see cref="CheatTableBuilder.Build"/>.</summary>
    public static List<CheatTableRow> BuildBatchRows(
        double walkPercent, double gravityPercent, double jumpHeightPercent)
    {
        return new List<CheatTableRow>
        {
            new CtScriptRow
            {
                Category = "Movement",
                Description = $"Move Speed ({Pct(walkPercent)})",
                Script = Generate(Knob.WalkSpeed, walkPercent),
            },
            new CtScriptRow
            {
                Category = "Movement",
                Description = $"Gravity ({Pct(gravityPercent)})",
                Script = Generate(Knob.Gravity, gravityPercent),
            },
            new CtScriptRow
            {
                Category = "Movement",
                Description = $"Super Jump ({Pct(jumpHeightPercent)} height)",
                Script = Generate(Knob.Jump, jumpHeightPercent),
            },
        };
    }

    private static string Label(Knob knob) => knob switch
    {
        Knob.WalkSpeed => "Move Speed",
        Knob.Gravity   => "Gravity",
        Knob.Jump      => "Super Jump",
        _              => "Movement",
    };

    private static string Pct(double percent) =>
        percent.ToString("0", CultureInfo.InvariantCulture) + "%";

    private static string Lua(double v) => v.ToString("0.0###", CultureInfo.InvariantCulture);

    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
