using System.Text;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates a CE memory-record AA Script for the GodMode toggle (Solitar).
///
/// A STATEFUL checkbox like <see cref="DebugCameraScriptGenerator"/>: ticking
/// runs <c>[ENABLE]</c> → mailbox <c>CMD_PROTECT</c> op <c>SET_GODMODE</c> value
/// 1 (force <c>AActor::bCanBeDamaged</c> FALSE on the local pawn), unticking runs
/// <c>[DISABLE]</c> → value 0 (restore). SELF-CONTAINED: talks to the
/// UE5Dumper.dll mailbox directly — no <c>ue5_invoke_helper.lua</c> needed. The
/// DLL owns the reflection, the bit write, and the re-assert worker (so the flag
/// survives respawns while the record is ticked).
/// </summary>
public static class ProtectionScriptGenerator
{
    // Mimic mailbox layout (must match dll/src/Mimic.h MailboxData + ProtectOp):
    //   0x00 cmd (write LAST to trigger) = CMD_PROTECT(9)
    //   0x04 status (poll == 1), 0x08 result (observed state / negative error)
    //   0x10 instanceAddr = op  (PROTECT_OP_SET_GODMODE = 0)
    //   0x18 ufuncAddr    = value (1 = ON / 0 = OFF)
    private const int CmdProtect = 9;
    private const int OpSetGodMode = 0;

    /// <summary>Build the [ENABLE]/[DISABLE] memory-record script.</summary>
    public static string Generate()
    {
        var sb = new StringBuilder(2048);
        EmitBlock(sb, "[ENABLE]", enable: true);
        EmitBlock(sb, "[DISABLE]", enable: false);
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, string header, bool enable)
    {
        var label = enable ? "ON" : "OFF";
        var value = enable ? 1 : 0;
        Line(sb, header);
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        CeLuaHygiene.AppendDebugPreamble(sb);
        Line(sb, "-- ================================================================");
        Line(sb, $"-- GodMode force {label} -- Generated by UE5CEDumper");
        Line(sb, "-- Tick = GodMode ON (AActor.bCanBeDamaged forced FALSE), untick = OFF.");
        Line(sb, "-- SELF-CONTAINED: talks to UE5Dumper.dll's mailbox directly -- no");
        Line(sb, "-- ue5_invoke_helper.lua needed. The DLL resolves the local pawn, writes");
        Line(sb, "-- the bitfield, and re-asserts it on a timer (survives respawns).");
        Line(sb, "-- Requires UE5Dumper.dll injected (version.dll proxy or CE inject).");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Resolve the exported mailbox symbol (tolerate the module-qualified form).
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "  showMessage('[GodMode] g_invokeMailbox not found -- is " +
                  "UE5Dumper.dll injected?')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb);

        // Mailbox round-trip: write op + value, trigger CMD_PROTECT=9, poll status.
        Line(sb, $"writeQword(mb + 0x10, {OpSetGodMode})    -- op: PROTECT_OP_SET_GODMODE");
        Line(sb, $"writeQword(mb + 0x18, {value})    -- value: {value} = {label}");
        Line(sb, "writeInteger(mb + 0x04, 0)    -- clear status");
        Line(sb, $"writeInteger(mb + 0x00, {CmdProtect})    -- CMD_PROTECT (write LAST)");
        Line(sb, "local elapsed = 0");
        Line(sb, "while readInteger(mb + 0x04) ~= 1 do");
        Line(sb, "  sleep(1)");
        Line(sb, "  elapsed = elapsed + 1");
        Line(sb, "  if elapsed >= 10000 then");
        Line(sb, "    showMessage('[GodMode] mailbox timeout (DLL not responding?)')");
        Line(sb, "    return");
        Line(sb, "  end");
        Line(sb, "end");
        Line(sb, "local state = readInteger(mb + 0x08)   -- 1=immune, 0=can be damaged, <0=error");
        Line(sb, $"dbg('[GodMode] {label} -> state=' .. tostring(state))");
        Line(sb, "if state < 0 then");
        Line(sb, $"  showMessage('[GodMode] {label} -- no pawn? (enter gameplay first)')");
        Line(sb, "elseif DEBUG == 0 then");
        Line(sb, $"  {CeLuaHygiene.CloseCall}   -- clean success: close the Lua Engine window");
        Line(sb, "end");
        Line(sb, "{$asm}");
    }

    /// <summary>Append a line with LF-only ending (no CR) for CE compatibility.</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
