using System.Globalization;
using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates per-action CE memory-record AA Scripts for Teleport, for users
/// who prefer .CT records (via <see cref="CheatTableBuilder"/>) over the
/// hotkey-bundle Lua (<see cref="TeleportLuaBundleGenerator"/>).
///
/// Every teleport action is MOMENTARY (not a stateful toggle like Debug
/// Camera), so each record's <c>[ENABLE]</c> fires the mailbox round-trip then
/// schedules a deferred self-untick (<c>createTimer</c>) so the checkbox clears
/// itself ~50 ms later; <c>[DISABLE]</c> is a nop. Self-contained: talks to the
/// Mimic mailbox directly, no helper-Lua dependency.
///
/// CE record-level hotkeys are NOT emitted here — bind keys via the Lua bundle
/// (<see cref="TeleportLuaBundleGenerator"/>) which is the hotkey path. See
/// docs/teleport-spec.md §9.2B.
/// </summary>
public static class TeleportScriptGenerator
{
    // Mailbox layout — see TeleportLuaBundleGenerator / dll/src/Mimic.h.
    private const int CmdTeleport = 8;

    public enum Action { Save, Recall, RecallLast, BugIt, BugItGo, Cursor, ClearAll }

    /// <summary>Build the [ENABLE]/[DISABLE] AA Script body for one action.</summary>
    public static string Generate(Action action, int slot = 0,
        double zOffset = 100.0, int channel = 0, bool fallbackCenter = true)
    {
        if (action == Action.ClearAll)
            return GenerateClearAll();

        int op = action switch
        {
            Action.Save => 1,
            Action.Recall => 2,
            Action.RecallLast => 7,   // TP_OP_RECALL_LAST (slot ignored)
            Action.BugIt => 9,        // TP_OP_BUGIT_SAVE  (store current pose)
            Action.BugItGo => 10,     // TP_OP_BUGIT_GO    (go to stored pose)
            Action.Cursor => 4,
            _ => 2,
        };
        string label = action switch
        {
            Action.Save => $"Save marker {slot + 1}",
            Action.Recall => $"Recall marker {slot + 1}",
            Action.RecallLast => "Recall last",
            Action.BugIt => "BugIt (store pose)",
            Action.BugItGo => "BugItGo (go to stored)",
            Action.Cursor => "Teleport to cursor",
            _ => "Teleport",
        };

        var sb = new StringBuilder(2048);
        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        Line(sb, "-- ================================================================");
        Line(sb, $"-- Teleport: {label} -- Generated by UE5CEDumper (self-contained)");
        Line(sb, "-- Momentary action: fires once, then auto-unticks. Talks to");
        Line(sb, "-- UE5Dumper.dll's mailbox directly (CMD_TELEPORT=8). Requires the");
        Line(sb, "-- DLL injected (version.dll proxy or CE inject).");
        Line(sb, "-- ================================================================");
        Line(sb);
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "  showMessage('[Teleport] g_invokeMailbox not found -- is UE5Dumper.dll injected?')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb);
        Line(sb, "if readInteger(mb + 0x00) == 0 then");
        if (op == 4)
        {
            Line(sb, $"  writeDouble(mb + 0x328, {Lua(zOffset)})   -- zOffset");
            Line(sb, $"  writeBytes(mb + 0x330, {channel & 0xFF})            -- trace channel");
            Line(sb, $"  writeBytes(mb + 0x331, {(fallbackCenter ? 1 : 0)})            -- fall back to screen center");
        }
        Line(sb, $"  writeQword(mb + 0x18, {slot})           -- slot");
        Line(sb, $"  writeQword(mb + 0x10, {op})             -- op");
        Line(sb, "  writeInteger(mb + 0x04, 0)             -- clear status");
        Line(sb, $"  writeInteger(mb + 0x00, {CmdTeleport})  -- CMD_TELEPORT (write LAST)");
        Line(sb, "  local elapsed = 0");
        Line(sb, "  while readInteger(mb + 0x04) ~= 1 do");
        Line(sb, "    sleep(1); elapsed = elapsed + 1");
        Line(sb, "    if elapsed >= 10000 then break end");
        Line(sb, "  end");
        Line(sb, "  local code = readInteger(mb + 0x08)");
        Line(sb, $"  print('[Teleport] {label} -> code=' .. code)");
        Line(sb, "  if code == -7 then");
        Line(sb, "    showMessage('[Teleport] marker saved on another map -- recall refused. " +
                 "Use the UI Force button.')");
        Line(sb, "  end");
        Line(sb, "end");
        Line(sb);
        Line(sb, "-- Deferred self-untick (avoids reentrancy on the activating thread).");
        Line(sb, "local t = createTimer(nil)");
        Line(sb, "t.Interval = 50");
        Line(sb, "t.OnTimer = function(timer)");
        Line(sb, "  timer.destroy()");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "end");
        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "-- momentary action -- nothing to undo");
        Line(sb, "{$asm}");
        return sb.ToString();
    }

    // Clears all 3 marker slots in one momentary record (op 6 = TP_OP_CLEAR_MARKER
    // per slot). Self-contained mailbox loop; auto-unticks like the others.
    private static string GenerateClearAll()
    {
        var sb = new StringBuilder(1536);
        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        Line(sb, "-- ================================================================");
        Line(sb, "-- Teleport: Clear all markers -- Generated by UE5CEDumper");
        Line(sb, "-- Momentary action: clears slots 1-3, then auto-unticks.");
        Line(sb, "-- ================================================================");
        Line(sb);
        Line(sb, "local mb = getAddressSafe('g_invokeMailbox')");
        Line(sb, "if not mb or mb == 0 then mb = getAddressSafe('UE5Dumper.g_invokeMailbox') end");
        Line(sb, "if not mb or mb == 0 then");
        Line(sb, "  showMessage('[Teleport] g_invokeMailbox not found -- is UE5Dumper.dll injected?')");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "  return");
        Line(sb, "end");
        Line(sb);
        Line(sb, "for slot = 0, 2 do");
        Line(sb, "  if readInteger(mb + 0x00) == 0 then");
        Line(sb, "    writeQword(mb + 0x18, slot)            -- slot");
        Line(sb, "    writeQword(mb + 0x10, 6)               -- op = CLEAR_MARKER");
        Line(sb, "    writeInteger(mb + 0x04, 0)             -- clear status");
        Line(sb, $"    writeInteger(mb + 0x00, {CmdTeleport})  -- CMD_TELEPORT (write LAST)");
        Line(sb, "    local elapsed = 0");
        Line(sb, "    while readInteger(mb + 0x04) ~= 1 do");
        Line(sb, "      sleep(1); elapsed = elapsed + 1");
        Line(sb, "      if elapsed >= 10000 then break end");
        Line(sb, "    end");
        Line(sb, "  end");
        Line(sb, "end");
        Line(sb, "print('[Teleport] all markers cleared')");
        Line(sb);
        Line(sb, "local t = createTimer(nil)");
        Line(sb, "t.Interval = 50");
        Line(sb, "t.OnTimer = function(timer)");
        Line(sb, "  timer.destroy()");
        Line(sb, "  if memrec then memrec.Active = false end");
        Line(sb, "end");
        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "-- momentary action -- nothing to undo");
        Line(sb, "{$asm}");
        return sb.ToString();
    }

    /// <summary>Build the standard 11-row .CT batch (Save 1-3, Recall 1-3,
    /// Recall last, BugIt, BugItGo, Cursor, Clear all) ready for
    /// <see cref="CheatTableBuilder.Build"/>.</summary>
    public static List<CheatTableRow> BuildBatchRows(
        double zOffset = 100.0, int channel = 0, bool fallbackCenter = true)
    {
        var rows = new List<CheatTableRow>();
        for (int i = 0; i < 3; i++)
            rows.Add(new CtScriptRow
            {
                Category = "Teleport",
                Description = $"Save marker {i + 1}",
                Script = Generate(Action.Save, i),
            });
        for (int i = 0; i < 3; i++)
            rows.Add(new CtScriptRow
            {
                Category = "Teleport",
                Description = $"Recall marker {i + 1}",
                Script = Generate(Action.Recall, i),
            });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "Recall last",
            Script = Generate(Action.RecallLast),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "BugIt (store pose)",
            Script = Generate(Action.BugIt),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "BugItGo (go to stored)",
            Script = Generate(Action.BugItGo),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "Teleport to cursor",
            Script = Generate(Action.Cursor, 0, zOffset, channel, fallbackCenter),
        });
        rows.Add(new CtScriptRow
        {
            Category = "Teleport",
            Description = "Clear all markers",
            Script = Generate(Action.ClearAll),
        });
        return rows;
    }

    private static string Lua(double v) => v.ToString("0.0###", CultureInfo.InvariantCulture);

    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }
}
